language: python

python:
  - "3.5"
  - "3.6"

install:
  - travis_retry pip install -r requirements.txt
  - travis_retry pip install coveralls

script:
  - coverage run --branch --source=mygpoauth ./manage.py test

after_script:
  - coveralls

sudo: false

env:
 - DATABASE_URL="postgres://postgres@localhost/mygpo_test"
