language: python

python:
  - "3.4"
  - "pypy3"

before_install:
    - sudo apt-get install -y libffi-dev

install:
  - travis_retry pip install -r requirements.txt
  - travis_retry pip install coveralls

script:
  - coverage run --branch --source=mygpoauth ./manage.py test

after_script:
  - coveralls

env:
 - DATABASE_URL="postgres://postgres@localhost/mygpo_test"
