language: python

dist: xenial

python:
  - "3.5"
  - "3.6"

sudo: true

services:
  - postgresql
addons:
  postgresql: "10"

before_script:
  - psql -c "ALTER USER travis WITH PASSWORD 'travis';"

install:
  - travis_retry pip install -r requirements.txt
  - travis_retry pip install coveralls

script:
  - coverage run --branch --source=mygpoauth ./manage.py test
  - make check-code-format

after_script:
  - coveralls

env:
 - DATABASE_URL="postgres://travis:travis@localhost/mygpo_test"
